name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    steps:
      - name: Just a placeholder
        run: echo "The 'stage' label was detected. Staging process starting!"
